micronaut:
  application:
    name: keymanagerrest
  server:
    netty:
      logLevel: TRACE

grpc:
  channels:
    keymanager:
      address: '${KEYMANAGER_SERVER:`localhost:50051`}'
      plaintext: true
      max-retry-attempts: 10

jackson:
  serialization:
    writeDatesAsTimestamps: false


